name = "sral-generator"
main = "src/index.ts"
compatibility_date = "2024-03-18"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[ai]
binding = "AI"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "sral-artifacts"
preview_bucket_name = "sral-artifacts-preview"

[[services]]
binding = "ORCHESTRATOR"
service = "sral-orchestrator"